### ISSUE TITLE
20231121-1721 u-boot for booting Armbian

### ISSUE THREAD

**Issue by matteoguglielmi** [chainsx/thead-u-boot#1]
I've followed the instructions on the Armbian website to install the latest:

**Armbian_community_24.8.0-trunk.205_Licheepi-4a_noble_current_6.6.14_minimal.img.xz**

by flashing your latest u-boot (20231121-1721).

Armbian boots correctly from the onboard eMMC, but the Armbian OS recognizes only 8 GB of memory out of 16 GB.

On the Sipeed WiKi page related to the 4A board, there is a **Memory Problem Repair Instructions** section, which involves flashing a patched u-boot binary file.

Therefore, I have tested installing the latest LPI4A_20240602 image provided by Sipeed, which comes with its own u-boot binary file, and in fact, the entire memory (16GB) is accessible on that OS.

I am now wondering if your u-boot binary is responsible for the missing 8GB of memory, or if it is the Armbian Linux kernel or dtb files responsible for it.

Thank you for any help on this issue.

**Comment by chainsx** [comment]
First, you need to flash 16GB u-boot. 
Second, you need to change "th1520-lichee-pi-4a.dts" to "th1520-lichee-pi-4a-16gb.dts" in /boot/extlinux/extlinux.conf.

**Comment by matteoguglielmi** [comment]
> First, you need to flash 16GB u-boot. Second, you need to change "th1520-lichee-pi-4a.dts" to "th1520-lichee-pi-4a-16gb.dts" in /boot/extlinux/extlinux.conf.

It worked.
